# Basic
title: WYK's Blog
author: WYK
description: For the shadow of lost knowledge at least protects you from many illusions.<br/> 知识，哪怕是知识的幻影，也会成为你的铠甲，保护你不被愚昧反噬。

url: "https://wyk2011fj.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    weibo:
    github: wyk2011fj
    mail: 357719970@qq.com
