# Basic
title: WangYuKai's Blog
author: WYK
description: Knowledge is a comfortable and necessary retreat and shelter for us in an advanced age；and if we do not plant it while young，it will give us no shade when one grows old.<br/> and if we do not plant it while young，it will give us no shade when one grows old

url: "https://wyk2011fj.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    weibo:
    github: wyk2011fj
    mail: 357719970@qq.com
